# SPDX-License-Identifier: GPL-3.0-or-later
"""Native Blender authoring panels and operators; never imports Kimodo or torch."""
import json
import math
import tempfile
from pathlib import Path
import numpy as np
import bpy
from bpy.props import StringProperty, IntProperty, EnumProperty, BoolProperty
from bpy_extras.io_utils import ImportHelper, ExportHelper
from mathutils import Vector
from . import ui, rig
from .authoring import (TRACKS, model_name, validate_record, compile_constraints,
                        native_to_records, load_authoring_json, normalize_project)
from .timeline import parse_prompts, frame_prompts, export_prompts, round_frame
from .motion_math import C, Clip, save_portable, forward_native

PROJECT_SETTINGS=('start_frame','source_start','source_end','preview_append','steps','seed',
                  'transition','context','blend','text_guidance','constraint_guidance',
                  'postprocess','num_samples','model')


def source_object(context):
    obj=context.scene.kimodo_studio.rig_source or context.object
    if obj is None or obj.type!='ARMATURE' or 'kimodo_skeleton_json' not in obj:
        raise ValueError('Choose a native Kimodo rig imported/generated by this add-on')
    if obj.name not in context.scene.objects:
        raise ValueError('Source rig belongs to another scene')
    return obj


def constraint_records(settings):
    records=[]
    for item in settings.constraints:
        payload=json.loads(item.payload)
        if item.target and item.kind=='root2d':
            p=C.T @ np.asarray(item.target.matrix_world.translation)
            payload['smooth_root_2d']=[p[[0,2]].tolist()]*len(payload['smooth_root_2d'])
        record={'name':item.name,'type':item.kind,'enabled':item.enabled,
                'start_frame':item.start_frame,'end_frame':item.end_frame,
                'payload':payload,'translation':list(item.translation)}
        meta=json.loads(item.skeleton)
        if meta:
            record['skeleton']=meta
        records.append(validate_record(record))
    return records


def put_record(settings, record):
    r=validate_record(record)
    item=settings.constraints.add()
    item.name=r.get('name',r['type']); item.kind=r['type']; item.enabled=r.get('enabled',True)
    item.start_frame=r['start_frame']; item.end_frame=r['end_frame']
    item.payload=json.dumps(r['payload']); item.skeleton=json.dumps(r.get('skeleton',{}))
    item.translation=r.get('translation',[0,0,0])
    settings.constraint_index=len(settings.constraints)-1
    return item


def sampled_record(context, kind, start, end):
    if end<start or end-start>1199:
        raise ValueError('Capture 1–1200 frames per interval')
    obj=source_object(context)
    with tempfile.TemporaryDirectory(prefix='kimodo-pose-') as tmp:
        clip=rig.snapshot(obj,context.scene,start,max(start+1,end),Path(tmp)/'pose.npz')
    count=end-start+1
    if kind=='root2d':
        payload={'smooth_root_2d':clip.root[:count,[0,2]].tolist()}
    else:
        payload={'local_rot_mats':clip.local[:count].tolist(),'root_positions':clip.root[:count].tolist()}
    return {'name':dict(TRACKS).get(kind,kind),'type':kind,'enabled':True,
            'start_frame':start,'end_frame':end,'payload':payload,
            'skeleton':json.loads(obj['kimodo_skeleton_json'])}


def select_only(context,obj):
    if context.mode!='OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')
    for selected in context.selected_objects:
        selected.select_set(False)
    obj.hide_set(False); obj.select_set(True); context.view_layer.objects.active=obj


def cleanup_editor(context):
    s=context.scene.kimodo_studio
    obj=s.edit_object
    if obj:
        if obj.mode!='OBJECT':
            context.view_layer.objects.active=obj; bpy.ops.object.mode_set(mode='OBJECT')
        arm=obj.data
        bpy.data.objects.remove(obj,do_unlink=True)
        if arm.users==0:
            bpy.data.armatures.remove(arm)
    s.edit_object=None; s.editing_index=-1
    if s.rig_source and s.rig_source.name in context.scene.objects:
        select_only(context,s.rig_source)


class KMD_OT_Capture(bpy.types.Operator):
    bl_idname='kimodo.capture_constraint'
    bl_label='Capture constraint'
    bl_options={'REGISTER','UNDO'}
    kind: EnumProperty(items=[(k,n,'') for k,n in TRACKS])
    start_frame: IntProperty(default=1)
    end_frame: IntProperty(default=1)
    use_playhead: BoolProperty(default=False)
    use_range: BoolProperty(default=False)

    def execute(self,context):
        s=context.scene.kimodo_studio
        try:
            if s.editing_index>=0:
                raise ValueError('Apply or cancel the current pose edit first')
            a,b=self.start_frame,self.end_frame
            kind=self.kind
            if self.use_playhead:
                a=b=context.scene.frame_current; kind=s.constraint_kind
            elif self.use_range:
                a,b=s.capture_start,s.capture_end; kind=s.constraint_kind
            if len(s.constraints)>=512:
                raise ValueError('Maximum 512 constraints')
            if kind=='root2d' and s.cursor_waypoint:
                v=C.T @ np.asarray(context.scene.cursor.location)
                rec={'type':kind,'name':'Root waypoint','start_frame':a,'end_frame':b,
                     'payload':{'smooth_root_2d':[v[[0,2]].tolist()]}}
            else:
                rec=sampled_record(context,kind,a,b)
            item=put_record(s,rec)
            if kind=='root2d' and s.cursor_waypoint:
                target=bpy.data.objects.new('Kimodo Root Waypoint',None)
                context.scene.collection.objects.link(target)
                target.empty_display_type='ARROWS'; target.empty_display_size=.18
                target.location=(context.scene.cursor.location.x,context.scene.cursor.location.y,0.)
                target['kimodo_waypoint']=True; item.target=target
            ui.redraw()
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_Constraint(bpy.types.Operator):
    bl_idname='kimodo.constraint_action'
    bl_label='Constraint action'
    bl_options={'REGISTER','UNDO'}
    action: EnumProperty(items=[(x,x.title(),'') for x in ('DELETE','DUPLICATE','GOTO','RECAPTURE','EDIT','APPLY','CANCEL')])

    def execute(self,context):
        s=context.scene.kimodo_studio
        try:
            if self.action=='CANCEL':
                cleanup_editor(context); return {'FINISHED'}
            if self.action=='APPLY':
                if s.editing_index<0 or not s.edit_object:
                    raise ValueError('No constraint pose is being edited')
                obj=s.edit_object
                if context.mode!='OBJECT':
                    bpy.ops.object.mode_set(mode='OBJECT')
                with tempfile.TemporaryDirectory() as tmp:
                    clip=rig.snapshot(obj,context.scene,context.scene.frame_current,
                                      context.scene.frame_current+1,Path(tmp)/'pose.npz')
                item=s.constraints[s.editing_index]
                p=json.loads(item.payload)
                p.update(local_rot_mats=clip.local[:1].tolist(),root_positions=clip.root[:1].tolist())
                item.payload=json.dumps(p); item.translation=(0,0,0)
                cleanup_editor(context); return {'FINISHED'}
            if s.editing_index>=0:
                raise ValueError('Apply or cancel the current edit first')
            if not s.constraints:
                raise ValueError('Select a constraint')
            i=max(0,min(s.constraint_index,len(s.constraints)-1)); item=s.constraints[i]
            if self.action=='DELETE':
                # User waypoint objects are retained; no hidden scene-object deletion.
                s.constraints.remove(i); s.constraint_index=max(0,i-1)
            elif self.action=='DUPLICATE':
                r=constraint_records(s)[i]; r['enabled']=False
                put_record(s,r)  # Muted duplicate avoids immediate same-track conflicts.
            elif self.action=='GOTO':
                context.scene.frame_set(item.start_frame)
                if item.target:
                    select_only(context,item.target)
            elif self.action=='RECAPTURE':
                r=sampled_record(context,item.kind,item.start_frame,item.end_frame)
                item.payload=json.dumps(r['payload']); item.skeleton=json.dumps(r['skeleton'])
            elif self.action=='EDIT':
                if item.kind=='root2d':
                    if item.target:
                        select_only(context,item.target)
                        return {'FINISHED'}
                    raise ValueError('For a root interval, adjust its offset or edit the source curve and recapture')
                r=constraint_records(s)[i]; meta=r.get('skeleton')
                if not meta:
                    meta=json.loads(source_object(context)['kimodo_skeleton_json'])
                local=np.asarray(r['payload']['local_rot_mats'][:1]); root=np.asarray(r['payload']['root_positions'][:1])
                local=np.repeat(local,2,axis=0); root=np.repeat(root,2,axis=0)
                root += C.T @ np.asarray(r.get('translation',[0,0,0]))
                if local.shape[1]!=len(meta['names']):
                    raise ValueError('Constraint pose and source skeleton differ')
                clip=Clip(local,root,rig.scene_fps(context.scene)).validate()
                context.scene.frame_set(item.start_frame)
                if context.mode!='OBJECT':
                    bpy.ops.object.mode_set(mode='OBJECT')
                with tempfile.TemporaryDirectory() as tmp:
                    path=Path(tmp)/'editor.npz'
                    save_portable(path,clip,meta,forward_native(local,root,meta))
                    for _,_,obj in rig.bake_motion(path,context.scene,item.start_frame,'Kimodo Constraint Edit'):
                        pass
                action=obj.animation_data.action
                obj.animation_data_clear(); action.use_fake_user=False
                if action.users==0:
                    bpy.data.actions.remove(action)
                obj['kimodo_constraint_editor']=True
                s.edit_object=obj; s.editing_index=i
                select_only(context,obj); bpy.ops.object.mode_set(mode='POSE')
            ui.redraw()
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_CurvePath(bpy.types.Operator):
    bl_idname='kimodo.curve_constraint'
    bl_label='Selected curve to 2D root path'
    bl_options={'REGISTER','UNDO'}

    def execute(self,context):
        try:
            obj=context.object; s=context.scene.kimodo_studio
            if not obj or obj.type!='CURVE' or len(obj.data.splines)!=1:
                raise ValueError('Select a curve with one POLY or Bezier spline')
            spline=obj.data.splines[0]; points=[]
            if spline.type=='POLY':
                points=[obj.matrix_world @ p.co.to_3d() for p in spline.points]
                if spline.use_cyclic_u and points:
                    points.append(points[0])
            elif spline.type=='BEZIER':
                from mathutils.geometry import interpolate_bezier
                ps=spline.bezier_points; count=len(ps) if spline.use_cyclic_u else len(ps)-1
                for i in range(count):
                    a,b=ps[i],ps[(i+1)%len(ps)]
                    samples=interpolate_bezier(a.co,a.handle_right,b.handle_left,b.co,max(3,spline.resolution_u+1))
                    points.extend(obj.matrix_world @ p for p in (samples if not points else samples[1:]))
            else:
                raise ValueError('Convert NURBS to a POLY or Bezier curve first')
            xy=np.asarray([[p.x,-p.y] for p in points])
            if len(xy)<2:
                raise ValueError('Path needs two or more points')
            distance=np.r_[0.,np.cumsum(np.linalg.norm(np.diff(xy,axis=0),axis=-1))]
            keep=np.r_[True,np.diff(distance)>1e-8]; xy,distance=xy[keep],distance[keep]
            n=s.capture_end-s.capture_start+1
            if len(xy)<2 or not 2<=n<=1200:
                raise ValueError('Use a non-zero-length path and a 2–1200-frame interval')
            t=np.linspace(0,distance[-1],n)
            path=np.stack([np.interp(t,distance,xy[:,axis]) for axis in range(2)],axis=-1)
            put_record(s,{'name':obj.name,'type':'root2d','start_frame':s.capture_start,'end_frame':s.capture_end,
                          'payload':{'smooth_root_2d':path.tolist()}})
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_ImportConstraints(bpy.types.Operator,ImportHelper):
    bl_idname='kimodo.import_constraints'; bl_label='Import native constraints JSON'
    bl_options={'REGISTER','UNDO'}
    filename_ext='.json'; filter_glob:StringProperty(default='*.json',options={'HIDDEN'})
    append: BoolProperty(name='Append instead of replace',default=False)
    def execute(self,context):
        s=context.scene.kimodo_studio
        try:
            if s.editing_index>=0:
                raise ValueError('Apply or cancel the pose edit first')
            records=native_to_records(load_authoring_json(self.filepath),s.constraint_import_fps,
                                      rig.scene_fps(context.scene),ui.timeline_origin(s))
            if len(records)+(len(s.constraints) if self.append else 0)>512:
                raise ValueError('Too many constraints')
            if not self.append:
                s.constraints.clear()
            for r in records:
                put_record(s,r)
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_ExportConstraints(bpy.types.Operator,ExportHelper):
    bl_idname='kimodo.export_constraints'; bl_label='Export native constraints JSON'
    filename_ext='.json'; filter_glob:StringProperty(default='*.json',options={'HIDDEN'})
    def execute(self,context):
        try:
            s=context.scene.kimodo_studio
            total=frame_prompts(ui.enabled_prompts(context.scene),s.constraint_import_fps)[-1].end
            native=compile_constraints(constraint_records(s),rig.scene_fps(context.scene),s.constraint_import_fps,
                                       ui.timeline_origin(s),total)
            Path(self.filepath).write_text(json.dumps(native,indent=2,allow_nan=False),encoding='utf-8')
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


def make_project(scene):
    s=scene.kimodo_studio
    settings={k:getattr(s,k) for k in PROJECT_SETTINGS}
    settings['model']=s.model if s.custom_model else model_name(s.dataset,s.skeleton_choice,s.version_choice)
    return normalize_project({'kind':'kimodo-studio-project','schema_version':2,'fps':rig.scene_fps(scene),
        'prompts':[{'text':p.text,'duration':p.duration,'enabled':p.enabled} for p in s.prompts],
        'constraints':constraint_records(s),'settings':settings})


def apply_project(scene,data):
    if scene.kimodo_studio.editing_index>=0:
        raise ValueError('Apply or cancel the constraint pose edit before loading a project')
    data=normalize_project(data)
    if abs(data['fps']-rig.scene_fps(scene))>.0001:
        raise ValueError(f"Project uses {data['fps']} FPS. Set the scene to that rate before importing")
    s=scene.kimodo_studio
    # Validate property bounds before mutating Blender state; do not silently clamp.
    for key,value in data['settings'].items():
        prop=s.bl_rna.properties[key]
        if isinstance(value,(int,float)) and not isinstance(value,bool):
            if not prop.hard_min<=value<=prop.hard_max:
                raise ValueError(f'Project setting {key} is outside the supported range')
    ui._SUSPEND_UPDATES=True
    try:
        s.prompts.clear(); s.constraints.clear()
        for row in data['prompts']:
            p=s.prompts.add(); p.text=row['text']; p.duration=float(row.get('duration',row.get('duration_seconds')))
            p.enabled=row.get('enabled',True)
        for r in data['constraints']:
            put_record(s,r)
        for key,value in data['settings'].items():
            setattr(s,key,value)
        if 'model' in data['settings']:
            s.custom_model=True
        s.index=0
    finally:
        ui._SUSPEND_UPDATES=False
    ui.update_markers(scene)


class KMD_OT_LoadProject(bpy.types.Operator,ImportHelper):
    bl_idname='kimodo.load_project'; bl_label='Load Studio project JSON'
    bl_options={'REGISTER','UNDO'}
    filename_ext='.json'; filter_glob:StringProperty(default='*.json',options={'HIDDEN'})
    def execute(self,context):
        try:
            apply_project(context.scene,load_authoring_json(self.filepath))
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_SaveProject(bpy.types.Operator,ExportHelper):
    bl_idname='kimodo.save_project'; bl_label='Save Studio project JSON'
    filename_ext='.json'; filter_glob:StringProperty(default='*.json',options={'HIDDEN'})
    def execute(self,context):
        try:
            Path(self.filepath).write_text(json.dumps(make_project(context.scene),indent=2,allow_nan=False),encoding='utf-8')
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_Example(bpy.types.Operator,ImportHelper):
    bl_idname='kimodo.load_example'; bl_label='Load example (select meta.json)'
    filename_ext='.json'; filter_glob:StringProperty(default='meta.json;*.json',options={'HIDDEN'})
    def execute(self,context):
        try:
            path=Path(self.filepath); data=load_authoring_json(path)
            prompts=parse_prompts(data); s=context.scene.kimodo_studio
            if s.editing_index>=0:
                raise ValueError('Apply or cancel the pose edit first')
            frame_prompts(prompts,rig.scene_fps(context.scene))
            constraint_path=path.parent/'constraints.json'
            records=native_to_records(load_authoring_json(constraint_path),s.constraint_import_fps,
                rig.scene_fps(context.scene),s.start_frame) if constraint_path.exists() else []
            ui._SUSPEND_UPDATES=True
            try:
                s.prompts.clear(); s.constraints.clear()
                for prompt in prompts:
                    item=s.prompts.add(); item.text=prompt.text; item.duration=float(prompt.duration)
                for r in records:
                    put_record(s,r)
                s.preview_append=False
            finally:
                ui._SUSPEND_UPDATES=False
            ui.update_markers(context.scene)
            motion=path.parent/'motion.npz'
            if motion.is_file():
                return bpy.ops.kimodo.run_job('INVOKE_DEFAULT',operation='import',source_file=str(motion))
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_Take(bpy.types.Operator):
    bl_idname='kimodo.take_action'; bl_label='Take action'
    bl_options={'REGISTER','UNDO'}
    action:EnumProperty(items=[(x,x.title(),'') for x in ('SELECT','SOURCE','SOLO','SHOW_ALL')])
    def execute(self,context):
        s=context.scene.kimodo_studio
        if not s.takes:
            return {'CANCELLED'}
        take=s.takes[max(0,min(s.take_index,len(s.takes)-1))]; obj=take.rig
        if obj is None or obj.name not in context.scene.objects:
            self.report({'ERROR'},'The take rig was deleted or moved to another scene'); return {'CANCELLED'}
        if self.action in {'SOLO','SHOW_ALL'}:
            for row in s.takes:
                if row.rig and row.rig.name in context.view_layer.objects:
                    row.rig.hide_set(self.action=='SOLO' and row.rig!=obj)
        else:
            select_only(context,obj)
            if self.action=='SOURCE':
                s.rig_source=obj
                s.source_start=math.ceil(obj.get('kimodo_frame_start',context.scene.frame_start))
                s.source_end=math.floor(obj.get('kimodo_frame_end',context.scene.frame_end))
                s.preview_append=True
        return {'FINISHED'}


class KMD_OT_Visualize(bpy.types.Operator):
    bl_idname='kimodo.visualize'; bl_label='Update visualization'
    bl_options={'REGISTER','UNDO'}
    action:EnumProperty(items=[(x,x.title(),'') for x in ('APPLY','FRAME','PATH')])
    def execute(self,context):
        try:
            s=context.scene.kimodo_studio; obj=source_object(context)
            if self.action=='PATH':
                with tempfile.TemporaryDirectory() as tmp:
                    clip=rig.snapshot(obj,context.scene,s.source_start,s.source_end,Path(tmp)/'path.npz')
                data=bpy.data.curves.new('Kimodo Root Trajectory','CURVE'); data.dimensions='3D'
                spline=data.splines.new('POLY'); spline.points.add(len(clip.root)-1)
                for p,point in zip(spline.points,clip.root @ C.T):
                    p.co=(*point,1.)
                data.bevel_depth=.008
                path=bpy.data.objects.new('Kimodo Root Trajectory',data); context.scene.collection.objects.link(path)
            else:
                obj.data.display_type=s.display_type; obj.data.show_names=s.show_names; obj.show_in_front=s.in_front
                for area in context.screen.areas:
                    if area.type=='VIEW_3D':
                        space=area.spaces.active; space.overlay.show_floor=s.show_floor; space.shading.type=s.viewport_shading
                        if self.action=='FRAME':
                            select_only(context,obj)
                            region=next((r for r in area.regions if r.type=='WINDOW'),None)
                            if region:
                                with context.temp_override(area=area,region=region):
                                    bpy.ops.view3d.view_selected(use_all_regions=False)
        except Exception as exc:
            self.report({'ERROR'},str(exc)); return {'CANCELLED'}
        return {'FINISHED'}


class KMD_OT_Workspace(bpy.types.Operator):
    bl_idname='kimodo.setup_workspace'; bl_label='Create Kimodo workspace'
    bl_description='Duplicate this workspace and prepare a native viewport/Dope Sheet layout'
    def execute(self,context):
        if ui._ACTIVE:
            self.report({'ERROR'},'Finish the current job first'); return {'CANCELLED'}
        bpy.ops.workspace.duplicate()
        context.workspace.name='Kimodo Motion Studio'
        areas=list(context.screen.areas)
        timeline=next((a for a in areas if a.type=='DOPESHEET_EDITOR'),None)
        if timeline is None:
            viewport=next((a for a in areas if a.type=='VIEW_3D'),None)
            if viewport:
                with context.temp_override(area=viewport):
                    bpy.ops.screen.area_split(direction='HORIZONTAL',factor=.28)
                views=[a for a in context.screen.areas if a.type=='VIEW_3D']
                timeline=min(views,key=lambda a:a.y)
        if timeline:
            timeline.type='DOPESHEET_EDITOR'; timeline.ui_type='DOPESHEET'
            timeline.spaces.active.show_region_ui=True
        for area in context.screen.areas:
            if area.type=='VIEW_3D':
                area.spaces.active.show_region_ui=True
        context.scene.kimodo_studio.overlay=True
        self.report({'INFO'},'Open the Kimodo sidebar; enlarge the Dope Sheet to reveal all tracks')
        return {'FINISHED'}


class KMD_UL_Constraints(bpy.types.UIList):
    def draw_item(self,context,layout,data,item,icon,active_data,active_propname,index):
        row=layout.row(align=True); row.prop(item,'enabled',text='')
        row.label(text=f'{item.name}  {item.start_frame}–{item.end_frame}')


class KMD_UL_Takes(bpy.types.UIList):
    def draw_item(self,context,layout,data,item,icon,active_data,active_propname,index):
        layout.label(text=f'{item.name}  · seed {item.seed}',icon='ACTION')


def controls(layout,context):
    scene=context.scene
    row=layout.row(align=True)
    row.operator('screen.frame_jump',text='',icon='REW').end=False
    row.operator('screen.keyframe_jump',text='',icon='PREV_KEYFRAME').next=False
    row.operator('screen.animation_play',text='',icon='PAUSE' if context.screen.is_animation_playing else 'PLAY')
    row.operator('screen.keyframe_jump',text='',icon='NEXT_KEYFRAME').next=True
    row.operator('screen.frame_jump',text='',icon='FF').end=True
    row.prop(scene,'frame_current',text='Frame')


def draw_panel(layout,context):
    s=context.scene.kimodo_studio
    layout.use_property_split=False
    controls(layout,context)
    layout.prop(s,'tab',text='')
    if s.tab=='GENERATE':
        box=layout.box(); box.label(text='Model selection',icon='ARMATURE_DATA')
        box.prop(s,'custom_model')
        if s.custom_model:
            box.prop(s,'model')
        else:
            box.prop(s,'dataset'); box.prop(s,'skeleton_choice'); box.prop(s,'version_choice')
            try:
                box.label(text=model_name(s.dataset,s.skeleton_choice,s.version_choice))
            except ValueError:
                box.label(text='This combination is unavailable; choose v1',icon='ERROR')
        box.operator('kimodo.run_job',text='Load model / create native rig',icon='ARMATURE_DATA').operation='prepare'
        row=layout.row(align=True)
        row.operator('kimodo.import_prompts',text='Import JSON',icon='IMPORT')
        row.operator('kimodo.export_prompts',text='Export JSON',icon='EXPORT')
        layout.template_list('KMD_UL_Prompts','',s,'prompts',s,'index',rows=4)
        row=layout.row(align=True)
        for action,icon in [('ADD','ADD'),('REMOVE','REMOVE'),('UP','TRIA_UP'),('DOWN','TRIA_DOWN')]:
            row.operator('kimodo.edit_prompt',text='',icon=icon).action=action
        if s.prompts:
            p=s.prompts[max(0,min(s.index,len(s.prompts)-1))]
            layout.prop(p,'text'); layout.prop(p,'duration')
        layout.prop(s,'start_frame'); layout.prop(s,'preview_append')
        try:
            total=frame_prompts(ui.enabled_prompts(context.scene),rig.scene_fps(context.scene))[-1].end
            layout.label(text=f'{total} frames / {total/rig.scene_fps(context.scene):.3f}s at scene FPS')
        except ValueError as exc:
            layout.label(text=str(exc)[:64],icon='INFO')
        box=layout.box(); box.label(text='Generation parameters')
        row=box.row(align=True); row.prop(s,'steps'); row.prop(s,'seed')
        box.prop(s,'num_samples'); box.prop(s,'transition'); box.prop(s,'heading'); box.prop(s,'align_first')
        row=box.row(align=True); row.prop(s,'text_guidance'); row.prop(s,'constraint_guidance')
        box.prop(s,'postprocess'); box.prop(s,'root_margin'); box.prop(s,'device')
        box=layout.box(); box.label(text='Continue existing animation')
        box.prop(s,'rig_source'); box.operator('kimodo.source_range')
        row=box.row(align=True); row.prop(s,'source_start'); row.prop(s,'source_end')
        box.prop(s,'context'); box.prop(s,'blend')
        row=layout.row(align=True)
        row.operator('kimodo.run_job',text='Generate',icon='PLAY').operation='generate'
        row.operator('kimodo.run_job',text='Continue from end').operation='continue'
    elif s.tab=='CONSTRAINTS':
        layout.prop(s,'rig_source'); layout.prop(s,'constraint_kind')
        layout.operator('kimodo.capture_constraint',text='Capture at playhead',icon='KEY_HLT').use_playhead=True
        row=layout.row(align=True); row.prop(s,'capture_start'); row.prop(s,'capture_end')
        layout.operator('kimodo.capture_constraint',text='Capture interval').use_range=True
        layout.prop(s,'cursor_waypoint')
        layout.operator('kimodo.curve_constraint',icon='CURVE_DATA')
        layout.template_list('KMD_UL_Constraints','',s,'constraints',s,'constraint_index',rows=5)
        if s.constraints:
            c=s.constraints[max(0,min(s.constraint_index,len(s.constraints)-1))]
            layout.prop(c,'name'); layout.label(text=dict(TRACKS).get(c.kind,c.kind))
            row=layout.row(align=True); row.prop(c,'start_frame'); row.prop(c,'end_frame')
            if c.kind in {'root2d','fullbody'}:
                layout.prop(c,'translation')
            if c.target:
                layout.prop(c.target,'location',text='Waypoint position')
            row=layout.row(align=True)
            for a,label in [('GOTO','Go to'),('DUPLICATE','Copy'),('DELETE','Delete')]:
                row.operator('kimodo.constraint_action',text=label).action=a
            row=layout.row(align=True)
            row.operator('kimodo.constraint_action',text='Edit pose / waypoint').action='EDIT'
            row.operator('kimodo.constraint_action',text='Recapture').action='RECAPTURE'
        if s.editing_index>=0:
            layout.label(text='Pose edit applies one pose across this interval',icon='INFO')
            row=layout.row(align=True)
            row.operator('kimodo.constraint_action',text='Apply edit').action='APPLY'
            row.operator('kimodo.constraint_action',text='Cancel edit').action='CANCEL'
        layout.label(text='Drag keys to move; Ctrl-drag a track to capture an interval')
    elif s.tab=='FILES':
        box=layout.box(); box.label(text='Prompts and projects')
        row=box.row(align=True); row.operator('kimodo.import_prompts'); row.operator('kimodo.export_prompts')
        row=box.row(align=True); row.operator('kimodo.load_project',text='Load project'); row.operator('kimodo.save_project',text='Save project')
        box.label(text='Projects store authoring data; save .blend for rigs/actions')
        box=layout.box(); box.label(text='Native constraints / examples')
        box.prop(s,'constraint_import_fps')
        row=box.row(align=True); row.operator('kimodo.import_constraints',text='Import constraints'); row.operator('kimodo.export_constraints',text='Export constraints')
        box.operator('kimodo.load_example',icon='FILE_FOLDER')
        box=layout.box(); box.label(text='Animation files')
        box.prop(s,'source_fps'); box.operator('kimodo.import_motion',icon='IMPORT')
        box.prop(s,'export_bvh')
        box.operator('kimodo.run_job',text='Export source rig / range',icon='EXPORT').operation='export'
        box.operator('kimodo.open_output',icon='FILE_FOLDER')
        pref=ui.preferences(context)
        box=layout.box(); box.label(text='External backend')
        box.prop(pref,'backend')
        if pref.backend=='WSL':
            box.prop(pref,'wsl_python'); box.prop(pref,'distro')
        else:
            box.prop(pref,'python_path')
        box.prop(pref,'repo_path'); box.prop(pref,'output_root'); box.prop(pref,'allow_downloads')
        box.operator('kimodo.run_job',text='Check backend imports').operation='check'
    elif s.tab=='VISUALIZE':
        layout.prop(s,'rig_source'); layout.prop(s,'display_type'); layout.prop(s,'show_names')
        layout.prop(s,'in_front'); layout.prop(s,'show_floor'); layout.prop(s,'viewport_shading')
        row=layout.row(align=True)
        row.operator('kimodo.visualize',text='Apply display').action='APPLY'
        row.operator('kimodo.visualize',text='Frame source').action='FRAME'
        layout.operator('kimodo.visualize',text='Build source root trajectory').action='PATH'
        layout.prop(s,'overlay'); layout.prop(s,'show_tracks'); layout.prop(s,'row_height')
        layout.operator('kimodo.setup_workspace',icon='WORKSPACE')
        layout.label(text='Native armatures; automatic SOMA mesh skinning not included')
    else:
        for text in ('Double-click a prompt to edit text.', 'Drag its right edge to ripple-trim duration.',
                     'Drag its body to reorder the sequence.', 'Click empty prompt row to append.',
                     'Right-click for the item menu.', 'Click a constraint track to capture a pose.',
                     'Ctrl-drag a track to capture an interval.', 'Drag constraints to move; edge-drag to retime.',
                     'Escape cancels the current drag.', 'Mouse wheel/MMB keep Blender navigation.',
                     'Use compatible native Kimodo rigs for continuation.',
                     'Gaps and overlapping text prompts are rejected.',
                     'Backend model weights are not bundled.',
                     'Alpha: real Blender/GPU validation remains required.'):
            layout.label(text=text)
    if s.takes:
        box=layout.box(); box.label(text='Motion takes')
        box.template_list('KMD_UL_Takes','',s,'takes',s,'take_index',rows=3)
        row=box.row(align=True)
        for action,label in [('SELECT','Select'),('SOURCE','Use as source'),('SOLO','Solo'),('SHOW_ALL','Show all')]:
            row.operator('kimodo.take_action',text=label).action=action
    if ui._ACTIVE:
        layout.operator('kimodo.cancel_job',icon='CANCEL')
    box=layout.box()
    for i in range(0,min(len(s.status),200),43):
        box.label(text=s.status[i:i+43])


def migrate_legacy():
    """Migrate earlier scaffold scene ID properties, without changing backend preferences."""
    for scene in bpy.data.scenes:
        old=scene.get('kimodo_motion')
        if old and not scene.kimodo_studio.prompts:
            try:
                for row in old.get('prompts',[]):
                    p=scene.kimodo_studio.prompts.add(); p.text=row.get('text','Motion')
                    p.duration=row.get('duration',6.); p.enabled=row.get('enabled',True)
            except (TypeError,AttributeError):
                pass


CLASSES=(KMD_OT_Capture,KMD_OT_Constraint,KMD_OT_CurvePath,KMD_OT_ImportConstraints,KMD_OT_ExportConstraints,
         KMD_OT_LoadProject,KMD_OT_SaveProject,KMD_OT_Example,KMD_OT_Take,KMD_OT_Visualize,KMD_OT_Workspace,
         KMD_UL_Constraints,KMD_UL_Takes)

def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)

def unregister():
    if bpy.context.scene and hasattr(bpy.types.Scene,'kimodo_studio') and bpy.context.scene.kimodo_studio.edit_object:
        cleanup_editor(bpy.context)
    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)
